export const UPDATE_AUTH_STATE = 'UPDATE_AUTH_STATE';
export const UPDATE_PENDING = 'UPDATE_PENDING';
export const UPDATE_VIDEO_SRC = 'UPDATE_VIDEO_SRC';
export const FETCH_VIDEO_RECORDS = 'FETCH_VIDEO_RECORDS';
export const CHECK_IF_USER_IS_LOGGED_IN = 'CHECK_IF_USER_IS_LOGGED_IN';